# Get user information
GET https://api.github.com/users/octocat

###

# List public repositories of the user
GET https://api.github.com/users/octocat/repos

###

# Get details of a specific repo
GET https://api.github.com/repos/octocat/Hello-World
Accept: application/vnd.github.v3+json

###

# (Optional) Get your private repos using token (replace YOUR_TOKEN)
GET https://api.github.com/user/repos
Authorization: Bearer YOUR_TOKEN
